/*  Message-number definitions derived from "MBBSEMU.MSG"  */

#define LEVEL6      0
#define STARTUP     1
#define INTRO       2
#define PROMPT      3
#define OUTPUT      4
#define MENU        5
#define BMENU       6
#define BADDMENU    7
#define BID         8
#define BSTR        9
#define BDELMENU   10
#define DBPRINT    11
#define DBPRINTE   12
#define DBVPRINT   13
#define INSFAIL    14
#define TMRINT     15
#define TMROUT     16
#define FLTOUT     17
#define LEVEL99    18
#define FSE        19
