/*  Message-number definitions derived from "MBBSEMU.MSG"  */

#define STARTUP     1
#define INTRO       2
#define PROMPT      3
#define OUTPUT      4
#define OPROMPT     5
#define OOUTPUT     6
#define MENU        7
#define BMENU       8
#define BADDMENU    9
#define BID        10
#define BSTR       11
#define BDELMENU   12
#define DBPRINT    13
#define DBPRINTE   14
#define DBVPRINT   15
#define INSFAIL    16
#define TMRINT     17
#define TMROUT     18
#define FLTOUT     19
#define FSE        21
